version: '3.1'

volumes:
  links_mongo_data:
    external: true

services:
  link-gtw:
    image: golang:latest
    env_file:
    - docker-compose.env
    volumes:
    - .:/go/src/github.com/ic2hrmk/links123/
    working_dir: /go/src/github.com/ic2hrmk/links123/
    command: go run ./entry/entry.go --kind=link-gtw --address=:8080
    restart: always

  link-srv:
    image: golang:latest
    env_file:
    - docker-compose.env
    volumes:
    - .:/go/src/github.com/ic2hrmk/links123/
    working_dir: /go/src/github.com/ic2hrmk/links123/
    command: go run ./entry/entry.go --kind=link-srv --address=:10001
    restart: always
    depends_on:
      - mongo

  #
  # 3-rd parties
  #
  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - links_mongo_data:/data/db

  mongo_express:
    image: mongo-express
    ports:
      - 7017:8081
    links:
      - mongo
    logging:
      driver: none
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    links:
    - "8081:80"
    volumes:
    - ./docker-compose.nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: none
