version: '3.1'

volumes:
  links_mongo_data:
    external: true

services:
  link-rest-gtw:
    image: golang:1.11-alpine
    env_file:
      - docker-compose.env
    volumes:
      - .:/go/src/github.com/ic2hrmk/links123/
    working_dir: /go/src/github.com/ic2hrmk/links123/
    command: go run ./entry/entry.go --kind=link-rest-gtw
    restart: always

  link-srv:
    image: golang:1.11-alpine
    env_file:
      - docker-compose.env
    volumes:
      - .:/go/src/github.com/ic2hrmk/links123/
    working_dir: /go/src/github.com/ic2hrmk/links123/
    command: go run ./entry/entry.go --kind=link-srv
    restart: always
    depends_on:
      - mongo

  #
  # 3-rd parties
  #
  mongo:
    image: mongo:3.4
    logging:
      driver: none
    volumes:
      - links_mongo_data:/data/db

  mongo_express:
    image: mongo-express:0.54.0
    ports:
      - 7017:8081
    links:
      - mongo
    logging:
      driver: none
    depends_on:
      - mongo

  nginx-rest-api:
    image: nginx:1.17.6
    ports:
      - "80:80"
    volumes:
      - ./docker-compose.restapi.nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
#    logging:
#      driver: none
    depends_on:
      - link-rest-gtw
