version: '3.3'

volumes:
  links_mongo_data:
    external: true

services:
  link-rest-gtw:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./compose/compose.env
    command: "--kind=link-rest-gtw"
    restart: always

  link-srv:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./compose/compose.env
    restart: always
    depends_on:
      - mongo
    command: "--kind=link-srv"

  #
  # 3-rd parties
  #
  mongo:
    image: mongo:3.4
    logging:
      driver: none
    volumes:
      - links_mongo_data:/data/db

  mongo_express:
    image: mongo-express:0.54.0
    ports:
      - 7017:8081
    links:
      - mongo
    logging:
      driver: none
    depends_on:
      - mongo

  nginx-rest-api:
    image: nginx:1.17.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./compose/nginx/api_conf.d/:/etc/nginx/api_conf.d/
      - ./compose/nginx/tls/:/etc/nginx/tls/
      - ./compose/nginx/api_backends.conf:/etc/nginx/api_backends.conf
      - ./compose/nginx/api_gateways.conf:/etc/nginx/api_gateways.conf
      - ./compose/nginx/api_json_errors.conf:/etc/nginx/api_json_errors.conf
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
