version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.1-stretch
    working_directory: /go/src/github.com/links-123/links123
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Download project dependencies
          command: |
            go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Build
          command: |
            make build


  build_images:
    working_directory: /go/src/github.com/links-123/links123
    docker:
      - image: docker:git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Docker Login
          command: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build and Push Image
          command: |
            TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            docker build -t links123/links123:$TAG .
            docker push links123/links123:$TAG

  deploy:
    docker:
      - image: docker:git
    steps:
      - run:
          name: Deployment
          command: |
            echo "Deployment triggered"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - development
      - build_images:
          requires:
            - build
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v\d[.]\d[.]\d.*/
      - deploy:
          type: approval
          requires:
            - build_images
          filters:
            tags:
              only: /^v\d[.]\d[.]\d.*/
