version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/ic2hrmk/links123
    steps:
      - checkout
      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/ic2hrmk/links123/vendor
      - run:
          name: Download project dependencies
          command: |
            make install-dependency-manager
            make run-dependency-manager
      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/ic2hrmk/links123/vendor
      - run:
          name: Build
          command: |
            make build


  deploy:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/ic2hrmk/links123
    steps:
      - run:
          name: Deployment
          command: |
            echo "Deployment triggered"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - development
      - deploy:
          type: approval
          filters:
            tags:
              only: /^v\d[.]\d[.]\d.*/
