version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    parallelism: 2
    working_directory: /go/src/github.com/ic2hrmk/links123
    steps:
      - checkout
      - run:
          name: Build
          command: |
            pwd
            ls -la
            make install-dependency-manager
            make run-dependency-manager
            make build

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
