name: CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.10'

      - name: Checkout code
        uses: actions/checkout@v1
        with:
          ref: development
          path: ~/go/src/github.com/${GITHUB_REPOSITORY}

      - name: Debug
          run: |
            pwd
            echo ${HOME}
            echo ${GITHUB_WORKSPACE}
            echo ${GOPATH}
            echo ${GOROOT}
          env:
            GOPATH: ~/go/src/github.com/${GITHUB_REPOSITORY}

      - name: Pre-Build setup
        run: |
          export PATH=$PATH:${GOPATH}/bin
          cd ~/go/src/github.com/${GITHUB_REPOSITORY}

      - name: Build
        run: |
          make install-dependency-manager
          make run-dependency-manager
          make build
