name: CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.10'

      - name: Checkout code
        uses: actions/checkout@v1
        with:
          ref: development

      - name: Pre-Build setup
        uses: cedrickring/golang-action@1.4.1
          with:
            args: echo Done!

      - name: Build
        run: |
          make install-dependency-manager
          make run-dependency-manager
          make build
