name: CI

on:
  push:
    branches: 
      - development

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.10'
      - uses: actions/checkout@v1
        with:
          ref: development
      - run: make build
